version: '3.5'

services:
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
  etcd-release:
    container_name: etcd-release
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes-release/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd-release:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  mall:
    image: mall
    container_name: mall
    environment:
      # 时区上海 - Timezone Shanghai
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    ports:
      - 8080:8080
      - 8001:8001
    working_dir: /go/mall
    volumes:
      - .:/go/mall
    privileged: true
    restart: always
