// Code generated by goctl. DO NOT EDIT.
package types

type UserReq struct {
	Id string `path:"id"`
}

type UserResponse struct {
	Id       string `json:"id"`
	Name     string `json:"username"`
	Password string `json:"password"`
}
